export const DATABASE = 'RADIX_DS';
export const PESSOA_REPOSITORY = 'PESSOA_REPOSITORY';
export const MISSAO_REPOSITORY = 'MISSAO_REPOSITORY';
export const SETOR_REPOSITORY = 'SETOR_REPOSITORY';
export const CELULA_REPOSITORY = 'CELULA_REPOSITORY';
export const DEVOLUCAO_REPOSITORY = 'DEVOLUCAO_REPOSITORY';
export const PERMISSAO_REPOSITORY = 'PERMISSAO_REPOSITORY';
