export const RADIX_DS = 'RADIX_DS';
export const PESSOA_REPOSITORY = 'PESSOA_REPOSITORY';
export const MISSAO_REPOSITORY = 'MISSAO_REPOSITORY';
export const SETOR_REPOSITORY = 'SETOR_REPOSITORY';
export const CELULA_REPOSITORY = 'CELULA_REPOSITORY';
