export const DATASOURCE = 'DATASOURCE';
export const PESSOA_REPOSITORY = 'PESSOA_REPOSITORY';
export const MISSAO_REPOSITORY = 'MISSAO_REPOSITORY';
export const SETOR_REPOSITORY = 'SETOR_REPOSITORY';
export const CELULA_REPOSITORY = 'CELULA_REPOSITORY';
export const DEVOLUCAO_REPOSITORY = 'DEVOLUCAO_REPOSITORY';
export const PERMISSAO_REPOSITORY = 'PERMISSAO_REPOSITORY';
export const CLIENT_NATS = 'CLIENT_NATS';

export const EVENTO_DEVOLUCAO_REALIZADA = 'devolucao-realizada';
export const EVENTO_ENVIO_LINK_PAGAMENTO = 'envio-link-pagamento';
